services:
  mysql-seervice:
    image: mysql:8
    networks:
     - app-network
  app-service:
    build: .
    container_name: task_backend
    restart: unless-stopped
    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      - mysql-service
